Linting, workflow and restructure (#5)
* Updated workflows. linting updates
* Restructure ansible-entrypoint diagnostics
* Linting fixes
* Update PR workflow trigger
* Explicit check for ansible.cfg

diff --git a/ansible-entrypoint b/ansible-entrypoint
--- a/ansible-entrypoint
+++ b/ansible-entrypoint
@@ -46,21 +46,43 @@ echo "New HOME directory: ${HOME}"
 
 # Set up venv for ansible
 echo ""
-echo "Configuring python environment"
+echo "Configuring python virtualenv"
 echo "----------------"
 python3 -m venv env
+# shellcheck disable=SC1091
 source ./env/bin/activate
+
+echo ""
+echo "Configuring pip"
+echo "----------------"
 python3 -m pip install --upgrade pip
 python3 -m pip install -r requirements.txt
+python3 -m pip list
 
 # Resolve ansible requirements
 echo ""
-echo "Configuring ansible environment"
+echo "Installing ansible collections"
 echo "----------------"
 ansible-galaxy collection install -r requirements.yml
+ansible-galaxy collection list
+
+echo ""
+echo "Installing ansible roles"
+echo "----------------"
+ansible-galaxy role install -r requirements.yml
+ansible-galaxy role list
 
 # Ansible config file
+echo ""
+echo "Setting ansible.cfg location"
+echo "----------------"
 export ANSIBLE_CONFIG="${WORKDIR}/ansible.cfg"
+if [ ! -f "${ANSIBLE_CONFIG}" ] ; then
+  echo "Missing ansible.cfg file: ${ANSIBLE_CONFIG}"
+  exit 1
+fi
+echo "ANSIBLE_CONFIG: ${ANSIBLE_CONFIG}"
+echo ""
 
 ########
 # Start ansible playbook
@@ -69,13 +91,10 @@ export ANSIBLE_CONFIG="${WORKDIR}/ansible.cfg"
 echo ""
 echo "Ansible runtime information"
 echo "----------------"
-echo "Ansible Install Location: "
-which ansible-playbook
+echo "Ansible Install Location: $(which ansible-playbook)"
 echo ""
 echo "Ansible-Playbook Version: "
 ansible-playbook --version
-echo ""
-echo "ANSIBLE_CONFIG: ${ANSIBLE_CONFIG}"
 echo ""
 
 # Move back to origin directory before starting the playbook
