Git config in promote script

diff --git a/azd_env_promote b/azd_env_promote
--- a/azd_env_promote
+++ b/azd_env_promote
@@ -8,7 +8,7 @@ set -o pipefail
 ########
 # Setup
 
-# azcli and jq must already be installed prior to running this script
+# Ensure relevant commands are available
 which az > /dev/null
 if [ $? -ne 0 ] ; then
   echo "Azure CLI is not installed"
@@ -18,6 +18,12 @@ fi
 which jq > /dev/null
 if [ $? -ne 0 ] ; then
   echo "jq is not installed"
+  exit 1
+fi
+
+which git > /dev/null
+if [ $? -ne 0 ] ; then
+  echo "git is not installed"
   exit 1
 fi
 
@@ -58,9 +64,6 @@ echo "Source Environment: ${SOURCE_ENV}"
 echo "Target Environment: $TARGET_ENV"
 echo ""
 
-########
-# Environment setup
-
 # Make sure we have the azure-devops extension installed
 echo ""
 echo "Ensuring azure-devops azcli extension is present"
@@ -70,3 +73,72 @@ if [ $? -ne 0 ] ; then
   exit 1
 fi
 
+########
+# Git information
+
+# Ensure we are on the source environment branch
+CURRENT_BRANCH=`git branch --show-current`
+echo "Current Branch: ${CURRENT_BRANCH}"
+if [ "$CURRENT_BRANCH" != "$SOURCE_ENV" ] ; then
+  echo "Not on correct branch to perform promotion"
+  exit 1
+fi
+
+# If this is a shallow clone, convert to a normal clone
+echo "Unshallow git repo"
+git fetch --unshallow
+
+# Fetching other branches
+echo "Fetching additional commits"
+git fetch --all || exit 1
+
+# Check if we have changes to promote
+git diff --exit-code "origin/${SOURCE_ENV}" "origin/${TARGET_ENV}"
+if [ $? -eq 0 ] ; then
+  echo "No changes from source to target. Not creating PR."
+  exit 0
+fi
+
+# Generate the description
+SOURCE_COMMITS=`git log --no-merges --no-decorate "origin/${SOURCE_ENV}" "^origin/${TARGET_ENV}" | head -20`
+TARGET_COMMITS=`git log --no-merges --no-decorate "origin/${TARGET_ENV}" "^origin/${SOURCE_ENV}" | head -20`
+DESCRIPTION="
+Promotion Details:
+\`\`\`
+Source Branch: $SOURCE_ENV
+Target Branch: $TARGET_ENV
+\`\`\`
+
+Change to promote (last 20):
+\`\`\`
+${SOURCE_COMMITS}
+\`\`\`
+
+Changes in target, but not in source (last 20):
+\`\`\`
+${TARGET_COMMITS}
+\`\`\`
+"
+echo "PR Description:"
+echo "${DESCRIPTION}"
+
+# Attempt to create a PR from the source to the target. Ignore failure as it
+# may already exist. If it's a failure for another reason, we'll catch that later.
+echo "Attempting to create PR - Ignore failure"
+az repos pr create --detect -s "${SOURCE_ENV}" -t "${TARGET_ENV}" --squash false \
+  --title "Promote ${SOURCE_ENV} to ${TARGET_ENV}" --description "${DESCRIPTION}"
+
+# Retrieve the PR, which we may have created or may have already existed
+echo "Retrieving PR for promotion"
+PR_ID=`az repos pr list -s "${SOURCE_ENV}" -t "${TARGET_ENV}" | jq '.[0].pullRequestId'`
+if [ $? -ne 0 ] ; then
+  echo "Failed to retrieve the ID for the promotion PR"
+  exit 1
+fi
+
+# Update the description on the PR
+az repos pr update --id "$PR_ID" --description "${DESCRIPTION}"
+if [ $? -ne 0 ] ; then
+  echo "Failed to update PR description"
+  exit 1
+fi
