Fix output for assert

diff --git a/exec_functions b/exec_functions
--- a/exec_functions
+++ b/exec_functions
@@ -8,9 +8,8 @@ set -o pipefail
 SEMVER_REGEX='^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$'
 
 function assert() {
-  echo "assert: $@"
   if ! "$@" ; then
-    echo "assertion ($@) failed"
+    echo "assertion ($@) failed" >&2
     exit 1
   fi
 }
